// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8up7n7a307hoPr_4wZIFPCR2E7TMq6gQ',
    appId: '1:275337336941:web:525c44f5a722412fddc764',
    messagingSenderId: '275337336941',
    projectId: 'chatapp-6e27c',
    authDomain: 'chatapp-6e27c.firebaseapp.com',
    storageBucket: 'chatapp-6e27c.appspot.com',
    measurementId: 'G-NY5ZCVC6R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP0KDk0dshuKpUeQiHkcU60-jyZA5-s1Y',
    appId: '1:275337336941:android:dfb6cef8bc4815e9ddc764',
    messagingSenderId: '275337336941',
    projectId: 'chatapp-6e27c',
    storageBucket: 'chatapp-6e27c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZlUmJ4yg3SIBem_ZiSZvaCi6ImM9ru8',
    appId: '1:275337336941:ios:d42742f1cdc9f438ddc764',
    messagingSenderId: '275337336941',
    projectId: 'chatapp-6e27c',
    storageBucket: 'chatapp-6e27c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}